### ISSUE TITLE
Add an experimental example

### ISSUE THREAD

**Issue by jan-janssen** [materialdigital/pyiron-workflow-mangement#2]
It would be great to add an experimental example - like the combination of pyiron pystem and temmeta Ning developed: 
https://github.com/NingWang1990/pyiron-pystem-temmeta

**Comment by max-hassani** [comment]
I have created the repository for the [experimental example](https://github.com/materialdigital/pyiron-workflow-TEMImageSegmentation). I want to update this repository and the notebook as well, but I can't create any branch, therefore I can not create a new PR in this repo. 
@jan-janssen, can you please change the role of me in the organization or give me access to this repository?

**Comment by jan-janssen** [comment]
@muh-hassani Sorry, I updated you to be an owner of this organisation.
